development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chester_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chester_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

cucumber:
  <<: *TEST
